#############################################################################
# Makefile for building: Obbjack
# Generated by qmake (2.01a) (Qt 4.8.2) on: jeu. août 15 17:48:33 2013
# Project:  Obbjack.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Obbjack.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -Isrc -Isrc/utils -Isrc/obbjack -Isrc/readFiles -Isrc/engine -Isrc/borrower -Isrc/object -Isrc/creatObj -Isrc/creatBor -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/borrower/borrower.cpp \
		src/creatBor/creatBor.cpp \
		src/creatObj/creatObj.cpp \
		src/engine/engine.cpp \
		src/obbjack/obbjack.cpp \
		src/object/object.cpp \
		src/readFiles/readFiles.cpp \
		src/utils/utils.cpp moc_creatBor.cpp \
		moc_creatObj.cpp \
		moc_obbjack.cpp
OBJECTS       = main.o \
		borrower.o \
		creatBor.o \
		creatObj.o \
		engine.o \
		obbjack.o \
		object.o \
		readFiles.o \
		utils.o \
		moc_creatBor.o \
		moc_creatObj.o \
		moc_obbjack.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Obbjack.pro
QMAKE_TARGET  = Obbjack
DESTDIR       = 
TARGET        = Obbjack

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Obbjack.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Obbjack.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Obbjack.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Obbjack1.0.0 || $(MKDIR) .tmp/Obbjack1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Obbjack1.0.0/ && $(COPY_FILE) --parents src/main.h src/borrower/borrower.h src/creatBor/creatBor.h src/creatObj/creatObj.h src/engine/engine.h src/obbjack/obbjack.h src/object/object.h src/readFiles/readFiles.h src/utils/utils.h .tmp/Obbjack1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/borrower/borrower.cpp src/creatBor/creatBor.cpp src/creatObj/creatObj.cpp src/engine/engine.cpp src/obbjack/obbjack.cpp src/object/object.cpp src/readFiles/readFiles.cpp src/utils/utils.cpp .tmp/Obbjack1.0.0/ && (cd `dirname .tmp/Obbjack1.0.0` && $(TAR) Obbjack1.0.0.tar Obbjack1.0.0 && $(COMPRESS) Obbjack1.0.0.tar) && $(MOVE) `dirname .tmp/Obbjack1.0.0`/Obbjack1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Obbjack1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_creatBor.cpp moc_creatObj.cpp moc_obbjack.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_creatBor.cpp moc_creatObj.cpp moc_obbjack.cpp
moc_creatBor.cpp: src/utils/utils.h \
		src/engine/engine.h \
		src/borrower/borrower.h \
		src/object/object.h \
		src/creatBor/creatBor.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/creatBor/creatBor.h -o moc_creatBor.cpp

moc_creatObj.cpp: src/utils/utils.h \
		src/engine/engine.h \
		src/borrower/borrower.h \
		src/object/object.h \
		src/creatObj/creatObj.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/creatObj/creatObj.h -o moc_creatObj.cpp

moc_obbjack.cpp: src/utils/utils.h \
		src/readFiles/readFiles.h \
		src/engine/engine.h \
		src/borrower/borrower.h \
		src/object/object.h \
		src/creatObj/creatObj.h \
		src/creatBor/creatBor.h \
		src/obbjack/obbjack.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) src/obbjack/obbjack.h -o moc_obbjack.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: src/main.cpp src/main.h \
		src/utils/utils.h \
		src/obbjack/obbjack.h \
		src/readFiles/readFiles.h \
		src/engine/engine.h \
		src/borrower/borrower.h \
		src/object/object.h \
		src/creatObj/creatObj.h \
		src/creatBor/creatBor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

borrower.o: src/borrower/borrower.cpp src/borrower/borrower.h \
		src/utils/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o borrower.o src/borrower/borrower.cpp

creatBor.o: src/creatBor/creatBor.cpp src/creatBor/creatBor.h \
		src/utils/utils.h \
		src/engine/engine.h \
		src/borrower/borrower.h \
		src/object/object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o creatBor.o src/creatBor/creatBor.cpp

creatObj.o: src/creatObj/creatObj.cpp src/creatObj/creatObj.h \
		src/utils/utils.h \
		src/engine/engine.h \
		src/borrower/borrower.h \
		src/object/object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o creatObj.o src/creatObj/creatObj.cpp

engine.o: src/engine/engine.cpp src/engine/engine.h \
		src/utils/utils.h \
		src/borrower/borrower.h \
		src/object/object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o engine.o src/engine/engine.cpp

obbjack.o: src/obbjack/obbjack.cpp src/main.h \
		src/utils/utils.h \
		src/obbjack/obbjack.h \
		src/readFiles/readFiles.h \
		src/engine/engine.h \
		src/borrower/borrower.h \
		src/object/object.h \
		src/creatObj/creatObj.h \
		src/creatBor/creatBor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obbjack.o src/obbjack/obbjack.cpp

object.o: src/object/object.cpp src/object/object.h \
		src/utils/utils.h \
		src/borrower/borrower.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o object.o src/object/object.cpp

readFiles.o: src/readFiles/readFiles.cpp src/readFiles/readFiles.h \
		src/utils/utils.h \
		src/engine/engine.h \
		src/borrower/borrower.h \
		src/object/object.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o readFiles.o src/readFiles/readFiles.cpp

utils.o: src/utils/utils.cpp src/utils/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o src/utils/utils.cpp

moc_creatBor.o: moc_creatBor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_creatBor.o moc_creatBor.cpp

moc_creatObj.o: moc_creatObj.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_creatObj.o moc_creatObj.cpp

moc_obbjack.o: moc_obbjack.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_obbjack.o moc_obbjack.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

